### ISSUE TITLE
tiro Doesn't work on some websites

### ISSUE THREAD

**Issue by jeffswt** [xmcp/tiroFinale#7]
Still doesn't work on GitHub when uploading releases. You did fix error #1... didn't you! Strange...

`XMLHttpRequest cannot load https://github-cloud.s3.amazonaws.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://github.com' is therefore not allowed access. The response had HTTP status code 504.`

![tirofinaleerror504](https://cloud.githubusercontent.com/assets/18145331/18276068/0f8e92b0-747c-11e6-8e28-fb8607b6d173.jpg)

**Comment by xmcp** [comment]
Please try to change `COMPRESS_THRESHOLD = 1` in `const.py` and tell me whether the HTTP 504 occurs again

**Comment by jeffswt** [comment]
It didn't work when I apply `COMPRESS_THRESHOLD = 1`. Either way, when it was uploading it consumed a great lot of memory (about 300 MB) and I strongly suspect that it was caused by the memory bugs.

HTTP 504 occurs again.

![tirofinale bug](https://cloud.githubusercontent.com/assets/18145331/18410118/7d0ab4c4-778b-11e6-90e3-ec2320949d94.jpg)

**Comment by jeffswt** [comment]
**And I used HTTPS.**

**Comment by xmcp** [comment]
click on the  504 response in the network panel and select `preview` tab to see the traceback. i'm unable to locate the bug without the traceback.

**Comment by xmcp** [comment]
v8.1 fixed a timeout-related bug (that big requests that cannot be sent in 15s will cause timeout error) and it might help.

try the new version _(don't forget to update `finale` as well)_ and see whether the bug is solved.

if not, please **attach the 504 traceback** or i'm not able to solve it.

p.s. about memory: tiro will temporarily use 3x memory for file uploading (compared to the upload file size). i probably won't improve it, as these RAMs are released immediately after the request completes.
